MADE-Game/TERRA2042

server/api/cards.js
server/api/collections.js
server/api/games.js
server/api/users.js

Added Routes for Users, Collections, Cards, and Games

Added routes - need testing

---

script/seed.js
server/api/games.js
server/auth/google.js
server/db/models/game.js
server/db/models/user.js
server/index.js

Translated sequelize logic for google login to mongoose. Getting an error of "failure to serialize user" after clicking "login with google"

Set up google login (needs fixing)

---

client/components/Board.js
client/components/Card.js
client/components/Side.js
client/store/game.js
public/style.css

Basic card component - based on dummy data.
Converted to a vertical card format. Linked to images, still needs complete style treatment.

Basic card component styling

---

client/components/Board.js
client/components/Card.js
client/components/Player.js
client/components/Side.js
client/engine/index.js
client/store/game.js

added win scenario and heroAttack

---

client/components/Board.js
client/components/Card.js
client/components/Plane.js
client/components/Side.js
client/engine/index.js
client/store/game.js
script/seed.js

pulls real data, minions die, cost works

---

client/app.js
client/components/Board.js
client/components/Chat.js
client/components/Games.js
client/routes.js
client/store/game.js
server/auth/google.js
server/index.js
server/socket/index.js

Users are able to send messages to other users through a "chat." Anybody that makes a connection to our website will see these messages. Namespace for game lobby is set up, need to implement individual rooms.

Sockets scaffold starting to take shape

---

client/components/Games.js
server/socket/index.js

Implemented the private room functionality

Private room

---

client/components/Board.js
client/store/game.js

fixed things

---

client/components/Card.js
client/components/Plane.js
client/components/Side.js
client/engine/index.js
client/store/reducers/player.js
client/store/thunksAndActionCreators.js

Fighters can only attack once, only five cards can be in play at once

---

client/components/Board.js
client/store/actionTypes.js
client/store/reducers/player.js
client/store/thunksAndActionCreators.js

fixed end turn button

---

client/components/Board.js
client/components/Side.js
client/store/actionTypes.js
client/store/reducers/game.js
client/store/reducers/opponent.js
client/store/reducers/player.js
client/store/thunksAndActionCreators.js
public/style.css
script/deploy
script/seed.js
server/api/games.js

---
State of the board survives a browser refresh.

Load and Save from db

---

client/components/Board.js
client/components/Side.js
client/components/index.js
client/components/navbar.js
client/components/user-home.js
client/routes.js
client/store/reducers/gameData.js
client/store/reducers/opponent.js
client/store/reducers/player.js
client/store/thunksAndActionCreators.js
script/seed.js
server/api/games.js
server/db/models/game.js
server/db/models/user.js
server/utils/index.js

Users can play a game with a user whos also associated.

---

client/components/Board.js
client/components/Chat.js
client/components/Games.js
client/components/Side.js
client/components/navbar.js
client/components/user-home.js
client/routes.js
client/store/thunksAndActionCreators.js
script/seed.js
server/index.js
server/socket/index.js

Moves are transmitted via sockets to other player and their board is updated real-time.

Opponent board is updated real-time

---

client/app.js
client/components/Card.js
client/components/Chat.js
client/components/Collection.js
client/components/CollectionList.js
client/components/DisplayCard.js
client/components/Side.js
client/components/navbar.js
client/components/user-home.js
client/index.js
client/routes.js
client/store/reducers/user.js
public/style.css
server/api/collections.js

Base level functionality for rendering dashboard on login, a component for a users collections, as well as a component for the cards in the currently selected collection.
I've noticed that the isLoggedIn boolean isn't being triggered when a user logs in, although the users info is being put into the redux store. This needs a fix before the components can be fleshed out further.

Collections

---

client/components/Board.js
client/components/Card.js
client/components/Side.js
client/store/reducers/gameData.js
client/store/reducers/opponent.js
client/store/reducers/player.js
client/store/thunksAndActionCreators.js
public/style.css
server/api/games.js
server/index.js
server/utils/index.js

Turn functionality fully implemented.

---

client/components/Games.js
client/components/Room.js
server/socket/index.js

two people can now play the same game

Two people can play!

---

client/components/Board.js
client/store/reducers/user.js
client/store/thunksAndActionCreators.js
server/api/collections.js
server/api/games.js
server/api/users.js
server/auth/index.js
server/db/models/user.js

a player's selected deck loads on new Game.

---

client/components/Board.js
server/api/games.js
server/auth/google.js
server/auth/index.js

assigned starter deck to google users

---

client/app.js
client/routes.js
server/auth/index.js

when not logged in, a user is always directed to login

---

client/components/Board.js
client/engine/index.js
client/store/actionTypes.js
client/store/reducers/gameData.js
client/store/reducers/player.js
client/store/thunksAndActionCreators.js
server/api/games.js

End turn increments settlers by 1

---

client/components/Collection.js
client/components/GamesLobby.js
client/routes.js
client/store/reducers/user.js
client/store/thunksAndActionCreators.js
server/api/games.js
server/auth/index.js
server/utils/index.js

New games pull selected decks, shuffle decks, randomizes p1 and populates hands

---

client/components/Card.js
client/components/Collection.js
client/components/CollectionList.js
client/components/GamesLobby.js
client/components/Plane.js
client/components/Player.js
client/components/Shop.js
client/components/user-home.js
client/index.js
client/store/reducers/player.js
client/store/reducers/user.js
package-lock.json
package.json
webpack.config.js

Changed alerts to toast notifications that disappear on their own. Also added ability to play and pause track

Toast Notifications

---

client/components/Collection.js
client/components/CollectionList.js
public/style.css

Styles added for collection/collections components

---

script/seed.js
server/api/cards.js
server/api/collections.js
server/api/games.js
server/api/users.js
server/db/models/user.js
server/utils/index.js

Route Permissions are controlled

---

client/components/History.js
client/components/user-home.js
client/routes.js
client/store/reducers/user.js
script/seed.js
server/api/cards.js
server/api/collections.js
server/api/games.js
server/api/users.js
server/db/models/user.js
server/utils/index.js

history page

---

client/components/Board.js
client/components/Card.js
client/components/GamesLobby.js
client/components/Plane.js
client/components/user-home.js
client/routes.js
server/api/collections.js
server/socket/index.js

Toast notifications for players leaving and entering game.

Toast notifications and Music volume

---

client/components/Board.js
client/components/GamesLobby.js
client/components/Room.js
client/components/Shop.js
client/components/user-home.js
client/routes.js
client/store/thunksAndActionCreators.js
package-lock.json
package.json
server/api/users.js
server/socket/index.js

Socket event listeners are now removed once the board component unmounts. This solves the issue of having multiple events fire for a single action.

Sockets multiple event listeners issue fixed

---

client/app.js
client/components/Board.js
client/components/Chat.js
client/components/GamesLobby.js
client/components/History.js
client/components/Side.js
client/store/thunksAndActionCreators.js
server/socket/index.js

A user now forfeits their turn if they don't complete their move within 20 seconds. Stats page is now styled. Also including some minor bug fixes on the end turn button and the lobby join button.

Forfeit turns and Styled stats page

---

script/catalog.js
script/seed.js

cards named, random shop cards still exist

---

client/components/Side.js

player now sees their own deck size

---

client/components/Board.js
client/components/Side.js
client/store/reducers/player.js

widened stutter, fixed draw card socket firing if cant draw card

---

client/components/Board.js
client/components/Side.js
server/api/games.js
server/utils/index.js

removed console logs

---

client/engine/index.js

small change to hoarder class

---

client/engine/index.js
script/catalog.js
script/seed.js
server/auth/google.js
server/auth/index.js

removed dummy cards and reduced starter of gold 5

---

client/components/Card.js
client/engine/index.js

New feature

---

client/components/CollectionList.js
client/components/IconButton.js

fixed broken animation in collection list

---

client/components/Button.js
client/components/Side.js

small button bug

---

client/components/Button.js
client/components/Side.js

Revert "small button bug"

---

client/components/user-home.js

made link to game rules open a new tab

---

client/components/Button.js
client/components/Side.js

fixed reverted bug

---

client/engine/index.js

medic fixed

---

client/components/user-home.js

changed link to rules

---

client/components/user-home.js

how to play

---

client/components/Badges.js
client/components/Board.js
client/components/Card.js
client/components/Chat.js
client/components/Collection.js
client/components/CollectionList.js
client/components/DisplayCard.js
client/components/Dropdown.js
client/components/GamesLobby.js
client/components/Player.js
client/components/Shop.js
client/components/ShopCard.js
client/components/Side.js
client/components/auth-form.js
client/store/reducers/opponent.js
public/style.css
server/api/games.js

Hero Icons added, minor style changes on a few other components

---

server/index.js

https redirect
